[package]
name = "fleet_commander"
version = "0.1.0"
authors = ["Expenses <expenses@airmail.cc>"]

[dependencies]
# OpenGL
glium = "*"
# model/uv loading
obj = {version = "*", features = ["genmesh"]}
genmesh = "*"
# image loading
image = {version = "*", default-features = false, features = ["png_codec"]}
# Useful wrapper around arrays
arrayvec = "*"
# Easier matrices stuff
cgmath = "*"
# collision detection extension for cgmath
collision = "*"
# 2d ui rendering (circles etc)
lyon = "*"
# text rendering
runic = {git = "https://github.com/expenses/runic"}
# lazy derive
derive_is_enum_variant = "*"
# Randomness
rand = "*"
# Serialization
serde = "*"
serde_derive = "*"
bincode = "*"
# UI
pedot = {git = "https://github.com/expenses/pedot"}
# error handling
failure = "*"
# logging
env_logger = {version = "*", default-features = false}
log = "*"
# 'retain_mut'
odds = {version = "*", features = ["std-vec"]}

[features]
embed_resources = []